# Introdução à Linguagem R

## Autor: Luiz Affonso Guedes
última atualização: outubro de 2017

## Objetivo

O objetivo geral deste documeto é apresentar a potencialidade da linguagem R. 
Os objetivos específicos deste documento são:
- Apresentar as principais funcionalidades da linguagem R, como tipos e estruturas de controle.
- Apresentar funções básicas de manipulação de dados na linguagem R.
- Tipos Vetores, Matrizes e Frames: uso, operações.
- Uso e definição de funções em linguagem R.
- Apresentar as funcionalidade de gráficos na linguagem R.

## Metodologia Utilizada
Usaremos uma abordagem interativa e incremental, mesclando breves explicações conceituais com programas em linguagem R.

# Sumário
- Introdução à linguagem R.
- Operadores e tipos de dados básicos
- Tipos de dados avançados e suas operações: vetores, matrizes, frames.
- Estruturas de controle
- Algumas funções úteis em R
- Uso e definição de função em R
    

## 0. Por quê a Linguagem R?

- R é uma ótima linguagem para iniciar sua jornada de ciência dos dados porque ela fornece um ambiente projetado desde o início para suportar a ciência dos dados. 
- R não é apenas uma linguagem de programação, mas também é um ambiente interativo para fazer ciência de dados. Para suportar a interação, R é uma linguagem muito mais flexível do que muitos dos seus pares. 
- Essa flexibilidade vem com suas desvantagens, mas a grande vantagem é como é fácil evoluir gramáticas personalizadas para partes específicas do processo de ciência dos dados. Essas mini linguagens ajudam você a pensar sobre problemas como cientista de dados, ao mesmo tempo em que oferece suporte à interação fluente entre o cérebro e o computador.

## 1. Operadores e Tipos Básicos de R

Operadores matematicos básicos em R
- Addition: +
- Subtraction: -
- Multiplication: *
- Division: /
- Exponentiation: ^
- Modulo: %%



# Header 1

In [ ]:
2 + 2

In [ ]:
# Aqui é um comentário em R

# Exemplo de uso de operadores em R
# Adição
5 + 5 

# Subtração
5 - 5 

# Multiplicação
3 * 5

 # Divisão
(5 + 5) / 2 

# Exponenciação
5 ^ 2

# Módulo
10%%3

Variáveis e atribuição de valor a variável

a <- 2

b = 3

Não esquecer que R é case sensitive

In [1]:
a <- 2
A <- 4
b = 3
c <- A-a

a
b
A
c

[1] 2

[1] 3

[1] 4

[1] 2

Alguns tipos básicos de dados em R
- Decimais, como 4.5: numerics.
- Naturais, como 4 - integers. Integers também são numerics.
- Boolean (TRUE or FALSE) - logical.
- Texto (ou string).


In [3]:
# Aqui é um comentário em R
# Exemplo do uso do operador atribuição em R

# Change my_numeric to be 42
my_numeric <- 42.5

# Change my_character to be "universe"
my_character <- 'some text'

# Change my_logical to be FALSE
my_logical <- TRUE

# Valors of Variables 
my_numeric
my_character
my_logical

[1] 42.5

[1] "some text"

[1] TRUE

## 2. Algumas funções úteis

Para verificar o tipo da variável em R - Utilizar função class()
- class(nome_da-variavel)
 
Para obter help de uma variável
- help(nome_da-variavel)
- ?nome_da-variavel

Para obter informação sobre os argumentos de uma função
- args(snome_da-variavel)

Para obter informação sobre as variáveis ativas no ambiente
- ls( )

In [7]:
# Check class of my_numeric
class(my_numeric)

# Check class of my_character
class(my_character)

# Check class of my_logical
class(my_logical)

print("Função args()")
texto <- "Alô, mundo!"

print(texto)

args(ls)
print("Função ls()")
ls()

[1] "numeric"

[1] "character"

[1] "logical"

[1] "Função args()"
[1] "Alô, mundo!"


function (name, pos = -1L, envir = as.environment(pos), all.names = FALSE, 
    pattern, sorted = TRUE) 
NULL

[1] "Função ls()"


[1] "a"            "A"            "b"            "c"            "my_character"
[6] "my_logical"   "my_numeric"   "texto"

## 3. Tipo vetor em R

Vetores são arrays unidimencionais que podem ser de "qualquer" tipo: numérico, lógico, decimais, etc.

- Em R, vetores são criados através da função c( ). 
- Os elementos dos vetores são separados por vírgulas.

 c(elemento1, elemento2, ...)
 

In [10]:
# Aqui é um comentário em R
# Exemplos de criação de vetores em R

numeric_vector <- c(1, 2, 3)
character_vector <- c("a", "b", "c")
boolean_vector <-c(TRUE, FALSE, TRUE)

numeric_vector
character_vector
boolean_vector

class(numeric_vector)
class(character_vector)
class(boolean_vector)

[1] 1 2 3

[1] "a" "b" "c"

[1]  TRUE FALSE  TRUE

[1] "numeric"

[1] "character"

[1] "logical"

- Também é possível utilizar a função names( ) para a criação de vetores:

names(nome_do_vetor)


In [14]:
# Aqui é um comentário em R
# Exemplo do uso da função name() para criar um vetor

some_vector <- c("John Doe", "poker player")
some_vector
names(some_vector) <- c("Name", "Profession")
some_vector

[1] "John Doe"     "poker player"

Name     Profession 
    "John Doe" "poker player"

- A seguir há mais alguns exemplo de criação de vetores em R


In [15]:
# Poker winnings from Monday to Friday
poker_vector <- c(140, -50, 20, -120, 240)
poker_vector

# Roulette winnings from Monday to Friday
roulette_vector <- c(-24, -50, 100, -350, 10)
roulette_vector

# Assign days as names of poker_vector
names(poker_vector) <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
poker_vector

# Assign days as names of roulette_vectors
names(roulette_vector) <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
roulette_vector

# Assign new days as names of roulette_vectors
names(roulette_vector) <- c("Segunda", "Terça", "Quarta", "Quinta", "Sexta")
roulette_vector

# Assign days as names of roulette_vectors
names(roulette_vector) <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
roulette_vector

[1]  140  -50   20 -120  240

[1]  -24  -50  100 -350   10

Monday   Tuesday Wednesday  Thursday    Friday 
      140       -50        20      -120       240

Monday   Tuesday Wednesday  Thursday    Friday 
      -24       -50       100      -350        10

Segunda   Terça  Quarta  Quinta   Sexta 
    -24     -50     100    -350      10

Monday   Tuesday Wednesday  Thursday    Friday 
      -24       -50       100      -350        10

### Exercício:
- Crie um vetor denominado de pais com os nomes dos seus pais.
- Crie um vetor denominado de idadePais, com a idade do seus pais.
- Nomear os índices dos vetores pais e idadePais para "Pai" e  "Mãe".


In [21]:
pais <- c("Angela", "Vanilson")
idadePais <- c("59", "54")

pais
idadePais

names(pais) <- c("Mãe", "Pai")
names(idadePais) <- c("Mãe", "Pai")
pais

[1] "Angela"   "Vanilson"

[1] "59" "54"

Mãe        Pai 
  "Angela" "Vanilson"

### 3.1 Operações com Vetores

- Para Soma e Subtração de vetores, utiliza-se os operadores + e -

C = A + B

D = A - B

In [22]:
print("Exemplo de soma e subtração de dois vetores")
A_vector <- c(1, 2, 3)
B_vector <- c(4, 5, 6)

# Soma de dois vetores é um vetor
total_vector <- A_vector + B_vector
total_vector

# Subtração de dois vetores é um vetor
diferenca_vector <- A_vector - B_vector
diferenca_vector


[1] "Exemplo de soma e subtração de dois vetores"


[1] 5 7 9

[1] -3 -3 -3

In [24]:
# Poker and roulette winnings from Monday to Friday:
print("Outro exemplo de soma de dois vetores")
poker_vector <- c(140, -50, 20, -120, 240)
roulette_vector <- c(-24, -50, 100, -350, 10)
days_vector <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
names(poker_vector) <- days_vector
names(roulette_vector) <- days_vector

# Assign to total_daily how much you won/lost on each day
total_daily <- poker_vector + roulette_vector
total_daily

[1] "Outro exemplo de soma de dois vetores"


Monday   Tuesday Wednesday  Thursday    Friday 
      116      -100       120      -470       250

- O resultado da Multiplicação ou Divisão de escalar por vetor é um vetor:

VetorB = c * VetorA

In [26]:
VetorA <- c(1,2,3,4)
c <- 2
VetorB <- c*VetorA
VetorC <- VetorA*c
VetorD <- VetorA/c
VetorE <- VetorA^c   # exemplo de potencição
VetorA
VetorB
VetorC
VetorD
VetorE

VetorA * VetorB

[1] 1 2 3 4

[1] 2 4 6 8

[1] 2 4 6 8

[1] 0.5 1.0 1.5 2.0

[1]  1  4  9 16

[1]  2  8 18 32

### Advertência
Em R, o operador * significa a multiplicação elemento a elemento entre dois vetores, retornando um vetor.

Então: vetor3 = vetor1 * vetor2; resulta em um vetor3, cujos seus elementos são o produto de elementos dos vetores vetor1 e vetor2.


In [27]:
print("Escreva um programa para exemplificar isto")

vetor1 <- c(1,2,1,2)
vetor2 <- c(1,2,3,4)
vetor3 <- vetor1*vetor2
vetor3

[1] "Escreva um programa para exemplificar isto"


[1] 1 4 3 8

- Para se obter a soma dos elementos de um vetor, utilize-se a função sum( ):

sum(vetorX)

In [30]:
print("Exemplo de soma de elementos de um vetor")
soma <- sum(VetorA)
str(soma)

[1] "Exemplo de soma de elementos de um vetor"
 num 10


#### Algumas funções úteis que operam sobre vetores:
- length(vetorX) ; obtém a dimensão do vetor
- mean(vetorX) ; obtém o valor médio dos valores dos elementos de um vetor
- max(vetorX); obtém o valor máximo entre os elementos de um vetor
- min(vetorX); obtém o valor mínimo entre os elementos de um vetor
- sd(vetorX); obtém o desvio padrão dos valores dos elementos de um vetor
- var(vetorX); obtém a variância dos valores dos elementos de um vetor
- median(vetorX); obtém a mediana dos valores dos elementos de um vetor

In [31]:
print("Programa exemplificando o uso de funções com vetores")
vetorX <- c(1,2,3,2,1)
length(vetorX)
mean(vetorX)
max(vetorX)
min(vetorX)
sd(vetorX)
var(vetorX)
median(vetorX)


[1] "Programa exemplificando o uso de funções com vetores"


[1] 5

[1] 1.8

[1] 3

[1] 1

[1] 0.83666

[1] 0.7

[1] 2

### 3.2 Acesso a elementos de um vetor:
- Para acessar elementos de um vetor (utiliza-se o mesmo procedimento para matrizes e frames) se utiliza [.].
- Entre os [.] se indica o elemento ou seguimento.
- Para acessar o 3º elemento do vetorX, usa-se vetorx[3].
- Para acessar do elemento 3 ao elemento 5 do vetorX, usa-se vetorx[3:5]

In [32]:
print("Programa para exemplificar como são acessados elementos de um vetor")
vetorX[3]
vetorX[c(3)]  # outra possibilidade
vetorX[c(3, 5)] # para acesso vários valores do vetor
vetorX[3:5]  # para acessar um intervalo no vetor


[1] "Programa para exemplificar como são acessados elementos de um vetor"


[1] 3

[1] 3

[1] 3 1

[1] 3 2 1

### 3.3 Uso de operadores lógicos de comparação com vetores

    < for less than
    > for greater than
    <= for less than or equal to
    >= for greater than or equal to
    == for equal to each other
    != not equal to each other
    & AND logical
    | OR logical

In [33]:
7> 3
3 != 3
TRUE & FALSE
TRUE | FALSE
c(4, 5, 6) > 5
vetorX
vetorX>=2
vetorX[vetorX>=2] #IRADO

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] FALSE FALSE  TRUE

[1] 1 2 3 2 1

[1] FALSE  TRUE  TRUE  TRUE FALSE

[1] 2 3 2

In [36]:
# The linkedin and facebook vectors have already been created for you
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
facebook <- c(17, 7, 5, 16, 8, 13, 14)

# Popular days
linkedin > 15

# Quiet days
linkedin <= 5

# LinkedIn more popular than Facebook
linkedin > facebook

last <- tail(linkedin, 1)
last <- tail(linkedin, 2)  # descomente essa linha para inferir o que faz a função tail()
last <- tail(linkedin, 3)
last

# Is last under 5 or above 10?
last < 5 | last > 10

# Is last between 15 (exclusive) and 20 (inclusive)?
last >15 & last <=20

[1]  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE

[1] FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] FALSE  TRUE  TRUE FALSE FALSE  TRUE FALSE

[1]  2 17 14

[1] TRUE TRUE TRUE

[1] FALSE  TRUE FALSE

## 4. Tipo Matriz em R
- Em R, uma matriz é uma coleção de elementos de um mesmo tipos de dados (numeric, character, or logical) disposta em estrutura bidimensional, descrita em linhas e colunas. 
- Usa-se a função matrix() para criar uma matriz.
- Uma matriz de 9 elementos em sequência, dispostos em 3 linhas, é definida por:
    - matrix(1:9, byrow = TRUE, nrow = 3)


In [41]:
# Exemplo de criação de uma matriz 3x3

matriz1= matrix(1:9, byrow = TRUE, nrow = 3)
matriz1

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [42]:
# Exemplo de criação de uma matriz 3x3
matriz2= matrix(11:19, byrow = TRUE, nrow = 3)
matriz2

[,1] [,2] [,3]
[1,] 11   12   13  
[2,] 14   15   16  
[3,] 17   18   19

#### Exercício:
- Crie uma Matriz 4x2, contendo os 8 primeiros números ímpares (1,3,5,..)

In [68]:
# Resolução do exercício:
a = c(1:100)
a = a[a%%2!=0]
a

args(matrix)
matrix(a[1:8], byrow=TRUE, nrow=4, ncol=2)

[1]  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
[26] 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99

function (data = NA, nrow = 1, ncol = 1, byrow = FALSE, dimnames = NULL) 
NULL

[,1] [,2]
[1,]  1    3  
[2,]  5    7  
[3,]  9   11  
[4,] 13   15

- Exemplo de outro modo de criação/iniciação de matrizes

In [69]:
A <- matrix(c(1,2,3,4,5,6),3,2)  # matrix 3x2
B <- matrix(c(1,2,3,4,5,6),2,3)  # matrix 2x3

In [70]:
print("Matriz A")
A
print("Matriz B")
B

[1] "Matriz A"


[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[1] "Matriz B"


[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [13]:
print(" Programa exemplificando outra forma de se criar matrizes" )
print("Os valores correspondem aos valores arrecadados nos EUA e nos outros países, respectivamente, com a trilogia Star Wars")

# Box office Star Wars (in millions!)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

# Create box_office
box_office <- c(new_hope, empire_strikes, return_jedi)
box_office
# Construct star_wars_matrix
star_wars_matrix <- matrix(box_office, byrow = TRUE, nrow = 3)
star_wars_matrix

[1] " Programa exemplificando outra forma de se criar matrizes"
[1] "Os valores correspondem aos valores arrecadados nos EUA e nos outros países, respectivamente, com a trilogia Star Wars"


[1] 460.998 314.400 290.475 247.900 309.306 165.800

[,1]    [,2] 
[1,] 460.998 314.4
[2,] 290.475 247.9
[3,] 309.306 165.8

De modo similar aos vetores, pode-se adicionar nomes às linhas e colunas de uma matriz

- rownames(my_matrix) <- row_names_vector

- colnames(my_matrix) <- col_names_vector

In [3]:
print("Outra forma de iniciar uma matriz")
teste <- matrix(2,5,3)
teste
colnames(teste) <- c("col1", "col2", "col3")
rownames(teste) <- c("row1", "row2", "row3", "row4","row5")
teste

[1] "Outra forma de iniciar uma matriz"


[,1] [,2] [,3]
[1,] 2    2    2   
[2,] 2    2    2   
[3,] 2    2    2   
[4,] 2    2    2   
[5,] 2    2    2

col1 col2 col3
row1 2    2    2   
row2 2    2    2   
row3 2    2    2   
row4 2    2    2   
row5 2    2    2

In [4]:
# Box office Star Wars (in millions!)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

# Construct matrix
star_wars_matrix <- matrix(c(new_hope, empire_strikes, return_jedi), nrow = 3, byrow = TRUE)

# Vectors region and titles, used for naming
region <- c("US", "non-US")
titles <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi")

# Name the columns with region
colnames(star_wars_matrix) <- region

# Name the rows with titles
rownames(star_wars_matrix) <- titles

# Print out star_wars_matrix

star_wars_matrix

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8

### 4.1 Algumas funções úteis para operar sobre matrizes
- rowSums(), retorna num vetor o cálculo do total para cada linha de uma matriz. 
- my_vector <- rowSums(my_matrix)
- a função colSums() é a dual da rowSums()


In [5]:
# Construct star_wars_matrix
box_office <- c(460.998, 314.4, 290.475, 247.900, 309.306, 165.8)
star_wars_matrix <- matrix(box_office, nrow = 3, byrow = TRUE,
                           dimnames = list(c("A New Hope", "The Empire Strikes Back", "Return of the Jedi"), 
                                           c("US", "non-US")))
star_wars_matrix

# Calculate worldwide box office figures
worldwide_vector <- rowSums(star_wars_matrix)
worldwide_vector

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8

A New Hope The Empire Strikes Back      Return of the Jedi 
                775.398                 538.375                 475.106

Pode-se adicionar uma ou múltiplas colunas para uma matriz com a função cbind( ). O resultado é uma matriz que anexa as matrizes por coluna:
- big_matrix <- cbind(matrix1, matrix2, vector1 ...)

A função rbind() é a dual da cbind( ), ou seja, nesse caso há a composição das matrizes por linha ou invés de por coluna.

In [6]:
# Construct star_wars_matrix
box_office <- c(460.998, 314.4, 290.475, 247.900, 309.306, 165.8)
star_wars_matrix <- matrix(box_office, nrow = 3, byrow = TRUE,
                           dimnames = list(c("A New Hope", "The Empire Strikes Back", "Return of the Jedi"), 
                                           c("US", "non-US")))

# The worldwide box office figures
worldwide_vector <- rowSums(star_wars_matrix)

# Bind the new variable worldwide_vector as a column to star_wars_matrix
all_wars_matrix <- cbind(star_wars_matrix,worldwide_vector)
all_wars_matrix

US      non-US worldwide_vector
A New Hope              460.998 314.4  775.398         
The Empire Strikes Back 290.475 247.9  538.375         
Return of the Jedi      309.306 165.8  475.106

In [7]:
box_office2 <- c(474.5,  552.5, 310.7 , 338.7, 380.3 , 468.5)
star_wars_matrix2<- matrix(box_office2, nrow = 3, byrow = TRUE,
                           dimnames = list(c("The Phantom Menace", "Attack of the Clones", "Revenge of the Sith"), 
                                           c("US", "non-US")))
all_wars_matrix <- rbind(star_wars_matrix,star_wars_matrix2)

star_wars_matrix
star_wars_matrix2
all_wars_matrix

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8

US    non-US
The Phantom Menace   474.5 552.5 
Attack of the Clones 310.7 338.7 
Revenge of the Sith  380.3 468.5

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8 
The Phantom Menace      474.500 552.5 
Attack of the Clones    310.700 338.7 
Revenge of the Sith     380.300 468.5

In [8]:
all_wars_matrix

worldwide_vector <- rowSums(all_wars_matrix)
all_wars_matrix <- cbind(all_wars_matrix,worldwide_vector)

total_vector <- colSums(all_wars_matrix)
all_wars_matrix <- rbind(all_wars_matrix,total_vector)
all_wars_matrix

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8 
The Phantom Menace      474.500 552.5 
Attack of the Clones    310.700 338.7 
Revenge of the Sith     380.300 468.5

US       non-US worldwide_vector
A New Hope               460.998  314.4  775.398        
The Empire Strikes Back  290.475  247.9  538.375        
Return of the Jedi       309.306  165.8  475.106        
The Phantom Menace       474.500  552.5 1027.000        
Attack of the Clones     310.700  338.7  649.400        
Revenge of the Sith      380.300  468.5  848.800        
total_vector            2226.279 2087.8 4314.079

### 4.2 Seleção de elementos de Matrizes:
- utiliza o mesmo priuncípio de acesso de elementos de vetores.
- no caso, se utiliza [.].
- como matrizes são bi-dimencionais, precisa-se utlizar vírgula [.,.].
- my_matrix[1,2] seleciona o elemento da linha 1 e coluna 2.
- my_matrix[1:3,2:4] resulta em uma matriz com dados das linhas 1, 2, 3 e colunas 2, 3, 4 da matriz my_matrix.

Se se deseja selecionar todos os elementos de uma linha ou coluna, é só não especificar a coluna ou linha, respectivamente.
- my_matrix[,1], seleciona todos os elementos da primeira coluna de my_matrix.
- my_matrix[2,], seleciona todos os elementos da segunda coluna de my_matrix.


In [9]:
# all_wars_matrix is available in your workspace
all_wars_matrix

# Select the non-US revenue for all movies
non_us_all <- all_wars_matrix[,2]
  
# Average non-US revenue
print("Valor médio de non_us_all =")
mean(non_us_all)
  
# Select the non-US revenue for first two movies
non_us_some <- all_wars_matrix[1:2,2]
  
# Average non-US revenue for first two movies
print("Valor médio de non_us_some =")
mean(non_us_some)

US       non-US worldwide_vector
A New Hope               460.998  314.4  775.398        
The Empire Strikes Back  290.475  247.9  538.375        
Return of the Jedi       309.306  165.8  475.106        
The Phantom Menace       474.500  552.5 1027.000        
Attack of the Clones     310.700  338.7  649.400        
Revenge of the Sith      380.300  468.5  848.800        
total_vector            2226.279 2087.8 4314.079

[1] "Valor médio de non_us_all ="


[1] 596.5143

[1] "Valor médio de non_us_some ="


[1] 281.15

### 4.3 Operação com Matrizes:
- operadores escalares
    - +, -, *, /
    - escalar com matriz returna uma matriz
    - duas matrizes, realizaoperação termo a termo

In [10]:
mat1 <- matrix(c(1,2,3,4,5,6),3,2) 
mat2 <- matrix(c(1,1,1,1,1,1),3,2)

mat1
mat2


[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[,1] [,2]
[1,] 1    1   
[2,] 1    1   
[3,] 1    1

#### Exercício -  Calcular e exibir os resultados das seguintes operações escalares sobre mat1 e mat2:
- soma
- subtração
- produto
- divisão

In [11]:
# Resolução do exercício

print("Operações elemento a elemento entre as matrizes") 
mat1 + mat2
mat1 - mat2
mat1 * mat2
mat1 / mat2

print("Operações elemento com escalar entre as matrizes")

2*mat1
mat1 - 1
mat2 + 1
mat2 / 10

[1] "Operações elemento a elemento entre as matrizes"


[,1] [,2]
[1,] 2    5   
[2,] 3    6   
[3,] 4    7

[,1] [,2]
[1,] 0    3   
[2,] 1    4   
[3,] 2    5

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[1] "Operações elemento com escalar entre as matrizes"


[,1] [,2]
[1,] 2     8  
[2,] 4    10  
[3,] 6    12

[,1] [,2]
[1,] 0    3   
[2,] 1    4   
[3,] 2    5

[,1] [,2]
[1,] 2    2   
[2,] 2    2   
[3,] 2    2

[,1] [,2]
[1,] 0.1  0.1 
[2,] 0.1  0.1 
[3,] 0.1  0.1

In [15]:
# all_wars_matrix and ticket_prices_matrix are available in your workspace
all_wars_matrix

ticket_prices_mat <- all_wars_matrix[1:6,1:2]


ticket_prices_mat[1,1] <- 5
ticket_prices_mat[1,2] <- 5
ticket_prices_mat[2,1] <- 6
ticket_prices_mat[2,2] <- 6
ticket_prices_mat[3,1] <- 7
ticket_prices_mat[3,2] <- 7
ticket_prices_mat[4,1] <- 4
ticket_prices_mat[4,2] <- 4
ticket_prices_mat[5,1] <- 4.5
ticket_prices_mat[5,2] <- 4.5
ticket_prices_mat[6,1] <- 4.9
ticket_prices_mat[6,2] <- 4.9


ticket_prices_mat

teste <- all_wars_matrix[1:6,1:2]
teste
# Estimated number of visitors

visitors <- all_wars_matrix[1:6,1:2] / ticket_prices_mat

# US visitors
us_visitors <- visitors[1:6,1]
us_visitors
# Average number of US visitors
mean(us_visitors)

US       non-US worldwide_vector
A New Hope               460.998  314.4  775.398        
The Empire Strikes Back  290.475  247.9  538.375        
Return of the Jedi       309.306  165.8  475.106        
The Phantom Menace       474.500  552.5 1027.000        
Attack of the Clones     310.700  338.7  649.400        
Revenge of the Sith      380.300  468.5  848.800        
total_vector            2226.279 2087.8 4314.079

US  non-US
A New Hope              5.0 5.0   
The Empire Strikes Back 6.0 6.0   
Return of the Jedi      7.0 7.0   
The Phantom Menace      4.0 4.0   
Attack of the Clones    4.5 4.5   
Revenge of the Sith     4.9 4.9

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8 
The Phantom Menace      474.500 552.5 
Attack of the Clones    310.700 338.7 
Revenge of the Sith     380.300 468.5

A New Hope The Empire Strikes Back      Return of the Jedi 
               92.19960                48.41250                44.18657 
     The Phantom Menace    Attack of the Clones     Revenge of the Sith 
              118.62500                69.04444                77.61224

[1] 75.01339

#### Dica: A Função summary( ) fornece uma visão rápida sobre o conteúdo das variáveis:
- summary(my_var)


In [16]:
summary(all_wars_matrix)

       US             non-US       worldwide_vector
 Min.   : 290.5   Min.   : 165.8   Min.   : 475.1  
 1st Qu.: 310.0   1st Qu.: 281.1   1st Qu.: 593.9  
 Median : 380.3   Median : 338.7   Median : 775.4  
 Mean   : 636.1   Mean   : 596.5   Mean   :1232.6  
 3rd Qu.: 467.7   3rd Qu.: 510.5   3rd Qu.: 937.9  
 Max.   :2226.3   Max.   :2087.8   Max.   :4314.1  

- operadores matriciais
    - %+%, %-%, %*%
    - solve(A),  corresponde à inversa da matriz A (para matrizes quadradas) 
    - t(A), corresponde à transposta da matriz A

In [27]:
mat1 <- matrix(c(1,2,3,4,5,6,7,8,9),3,3) 
mat2 <- matrix(c(1,1,1,1,1,1,1,1,1),3,3)
identidade3 = I10 <- diag(1,3)  # matriz identidade 3x3

In [28]:
identidade3

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

#### Exercício: Obter
- Inversa de Identidade3
- Transposta de mat1
- produto matricial entre mat1 e mat2
- Soma matricial de mat1 e mat2 ??

In [35]:
# Resolução do exercício:
solve(identidade3)
t(identidade3)
mat1 %*% mat2
mat1 + mat2

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

[,1] [,2] [,3]
[1,] 12   12   12  
[2,] 15   15   15  
[3,] 18   18   18

[,1] [,2] [,3]
[1,] 2    5     8  
[2,] 3    6     9  
[3,] 4    7    10

### 4.3 Comparação entre matrizes
- realizado de forma similar a com vetores

In [36]:
# The social data has been created for you
linkedin <- c(16, 9, 13, 5, 2, 17, 14)
facebook <- c(17, 7, 5, 16, 8, 13, 14)
views <- matrix(c(linkedin, facebook), nrow = 2, byrow = TRUE)

# When does views equal 13?
views == 13

# When is views less than or equal to 14?
views <= 14

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7] 
[1,] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE

[,1]  [,2] [,3] [,4]  [,5] [,6]  [,7]
[1,] FALSE TRUE TRUE  TRUE TRUE FALSE TRUE
[2,] FALSE TRUE TRUE FALSE TRUE  TRUE TRUE

In [37]:
print("Outra forma de iniciar uma matriz")
teste <- matrix(2,5,3)
teste

[1] "Outra forma de iniciar uma matriz"


[,1] [,2] [,3]
[1,] 2    2    2   
[2,] 2    2    2   
[3,] 2    2    2   
[4,] 2    2    2   
[5,] 2    2    2

## 5. Tipo Frame em R

- Estrutura bidimensional, onde as colunas não precisam ter elementos do mesmo tipo, como no caso das matrizes.
- No data.frame cada coluna representa uma variável e cada linha uma observação.
- Equivale aos dados de planilha.

### 5.1 Criação de data.frame
- Usar a função data.frame()

In [38]:
# Exemplo de Craição de data.frame

alunos <- data.frame(nome = c("João", "Clara", "Miguel", "Mariana"),
                           sexo = c("M", "F", "M", "F"),
                           idade = c(21,23, 22, 21),
                           stringsAsFactors = FALSE)

In [39]:
alunos

nome    sexo idade
1 João    M    21   
2 Clara   F    23   
3 Miguel  M    22   
4 Mariana F    21

In [41]:
str(alunos)

'data.frame':	4 obs. of  3 variables:
 $ nome : chr  "João" "Clara" "Miguel" "Mariana"
 $ sexo : chr  "M" "F" "M" "F"
 $ idade: num  21 23 22 21


#### Analise o que fazem as funções:
- rownames(data.frame)
- colnames(data.frame)
- names(data.frame)

In [42]:
rownames(alunos)
colnames(alunos)
names(alunos)

[1] "1" "2" "3" "4"

[1] "nome"  "sexo"  "idade"

[1] "nome"  "sexo"  "idade"

### 5.1 Manipulação de Elementos de data.frame
- Segue procedimento muito similar à manipulação de matrizes.
    - acesso a elementos do data.frame.
    - modificar elementos do data.frame.
    

#### Acesso a elementos de data.frames

In [43]:
alunos

nome    sexo idade
1 João    M    21   
2 Clara   F    23   
3 Miguel  M    22   
4 Mariana F    21

In [44]:
alunos[1, 1]

[1] "João"

In [48]:
alunos[1, 1, drop = FALSE]
alunos[1, 1, drop = TRUE]

nome
1 João

[1] "João"

In [49]:
alunos[,1:2]

nome    sexo
1 João    M   
2 Clara   F   
3 Miguel  M   
4 Mariana F

In [50]:
alunos[-1, ]

nome    sexo idade
2 Clara   F    23   
3 Miguel  M    22   
4 Mariana F    21

In [51]:
## seleciona linha 3, colunas "nome" e "iade"
alunos[3 , c("nome", "idade")]

nome   idade
3 Miguel 22

In [52]:
# exercício: Selecione as duas últimas linhas
alunos[3:4,]

nome    sexo idade
3 Miguel  M    22   
4 Mariana F    21

#### Modificação de elementos de data.frames

In [53]:
alunos

nome    sexo idade
1 João    M    21   
2 Clara   F    23   
3 Miguel  M    22   
4 Mariana F    21

In [54]:
## Aniversário de Clara - aumento da idade de Clara
alunos[2, "idade"] <- alunos[2, "idade"] + 1

In [55]:
alunos

nome    sexo idade
1 João    M    21   
2 Clara   F    24   
3 Miguel  M    22   
4 Mariana F    21

### 5.2 Outras Formas para Manipulação de Elementos de data.frames
- Pode-se acessar e modificar elementos de data.frame utilizando o operador $ e a lista [[ ]]
- Ambos sempre retornam um vetor como resultado.

In [56]:
## Seleciona coluna nome
alunos$nome

## Seleciona coluna nome 
alunos[["nome"]]

[1] "João"    "Clara"   "Miguel"  "Mariana"

[1] "João"    "Clara"   "Miguel"  "Mariana"

In [65]:
## Exercício: Selecione a coluna 'idade' no data.frame alunos
alunos[,c("idade"),drop=FALSE]
alunos$idade
alunos[["idade"]]

idade
1 21   
2 24   
3 22   
4 21

[1] 21 24 22 21

[1] 21 24 22 21

#### Também é possível alterar valor combinando $ ou [[ ]] com <-:

In [70]:
## Aniversário de João
alunos$idade[1] <- alunos$idade[1] + 1
 
## equivalente
alunos[["idade"]][1] <- alunos[["idade"]][1] + 1


alunos

nome    sexo idade
1 João    M    30   
2 Clara   F    24   
3 Miguel  M    22   
4 Mariana F    21

#### Advertência: o retorno da operação pode ser vertor ou data.frame
- df[ ,"x"]                - retorna a coluna x do data.frame df como tipo vetor.
- df$x                     - retorna a coluna x do data.frame df como tipo vetor.
- df[ , "x", drop = FALSE] - retorna a coluna x do data.frame df como tipo data.frame.
- df["x"]                  - retorna a coluna x do data.frame df como tipo data.frame.

In [71]:
## Retorna data.frame
alunos[ ,"idade", drop = FALSE]

 
## Retorna data.frame
alunos["idade"]


idade
1 30   
2 24   
3 22   
4 21

idade
1 30   
2 24   
3 22   
4 21

In [72]:
## Retorna vetor
alunos$idade

 
## Retorna vetor
alunos[ ,"idade"]


[1] 30 24 22 21

[1] 30 24 22 21

### 5.3 Adicionar Colunas e Linhas em data.frame
- Há várias forma de se adicionar e remover colunas em data.frames
- Para adicionar, pode utilizar $, [ , ],  [[ ]] ou com cbind().

In [73]:
# Adição de coluna no data.frame alunos

# utilizando df$nova_coluna
alunos$curso <- c("Engenharia Mecatrônica", "Engenharia de Computação", "Engenharia de Computação", "Engenharia de Computação" )

# utilizando [[]]
alunos[["altura"]] <- c(1.71, 1.55, 1.82, 1.63)

# utilizando [ , "nova_coluna"]
alunos[, "peso"] <- c(88.1, 55.2, 72.6, 61.1)

# Utilizando matrizes
alunos <- cbind(alunos, clube = c("ABC", "América", "Alecrim", "Potiguar"),
                      stringsAsFactors = FALSE)


In [74]:
alunos

nome    sexo idade curso                    altura peso clube   
1 João    M    30    Engenharia Mecatrônica   1.71   88.1 ABC     
2 Clara   F    24    Engenharia de Computação 1.55   55.2 América 
3 Miguel  M    22    Engenharia de Computação 1.82   72.6 Alecrim 
4 Mariana F    21    Engenharia de Computação 1.63   61.1 Potiguar

#### Inclusão de nova linha
- Basta atribuir uma nova linha ao data.frame.
- Mas, se os elementos têm colunas de tipos diferentes, use a função data.frame
   - para evitar que todas as colunas do o data.frame sejam transformadas num memso tipo.

In [75]:
# Inclusão de uma nova linhas
alunos[4, ] <- data.frame(nome = "Ênio", sexo = "M", idade = 21, curso = "Engenharia Mecatrônica",
                          altura = 1.68, peso = 63.2,clube = "Tashima",
                                stringsAsFactors = FALSE)

In [76]:
alunos

nome   sexo idade curso                    altura peso clube  
1 João   M    30    Engenharia Mecatrônica   1.71   88.1 ABC    
2 Clara  F    24    Engenharia de Computação 1.55   55.2 América
3 Miguel M    22    Engenharia de Computação 1.82   72.6 Alecrim
4 Ênio   M    21    Engenharia Mecatrônica   1.68   63.2 Tashima

- Outra maneira, é utilizando a finção rbind( ).

In [83]:
# Inclusão de uma nova linha
rbind(alunos, data.frame(nome = "Amanda", sexo = "F", idade = 20, curso = "Engenharia de Computação",
                         altura = 1.65, peso = 62.1, clube = "ABC", 
                                stringsAsFactors = FALSE))

nome   sexo idade curso                    altura peso clube  
1 João   M    30    Engenharia Mecatrônica   1.71   88.1 ABC    
2 Clara  F    24    Engenharia de Computação 1.55   55.2 América
3 Miguel M    22    Engenharia de Computação 1.82   72.6 Alecrim
4 Ênio   M    21    Engenharia Mecatrônica   1.68   63.2 Tashima
5 Amanda F    20    Engenharia de Computação 1.65   62.1 ABC

In [86]:
alunos[4:5,]
alunos

nome sexo idade curso                  altura peso clube  
4  Ênio M    21    Engenharia Mecatrônica 1.68   63.2 Tashima
NA NA   NA   NA    NA                       NA     NA NA

nome   sexo idade curso                    altura peso clube  
1 João   M    30    Engenharia Mecatrônica   1.71   88.1 ABC    
2 Clara  F    24    Engenharia de Computação 1.55   55.2 América
3 Miguel M    22    Engenharia de Computação 1.82   72.6 Alecrim
4 Ênio   M    21    Engenharia Mecatrônica   1.68   63.2 Tashima

#### Exercício: 
- Crie uma nova coluna com o IMC dos Alunos.
   - IMC = peso/(altura ou quadrado)
   - Calcule a média do IMC dos alunos.

In [120]:
# Exercício

alunos$IMC <- c(alunos[,6]/(alunos[,5])^2)
alunos

nome   sexo idade curso                    altura peso clube   IMC     
1 João   M    30    Engenharia Mecatrônica   1.71   88.1 ABC     30.12893
2 Clara  F    24    Engenharia de Computação 1.55   55.2 América 22.97607
3 Miguel M    22    Engenharia de Computação 1.82   72.6 Alecrim 21.91764
4 Ênio   M    21    Engenharia Mecatrônica   1.68   63.2 Tashima 22.39229

### 5.3 Remover Colunas e Linhas em data.frame

- Para remover uma remover uma coluna de um data.frame basta atribuir o valor NULL a ela.
   - alunos$clube <- NULL
   
   
- Removendo linhas de um data.frame basta selecionar apenas aquelas linhas que você deseja manter:
  - alunos <- alunos[1:3, ]  # mantém as 03 primeiras linhas
  - alunos <- alunos[alunos$peso > 65  # mantém os alunos com peso acima de 65 kilos

#### Exercício:
- Obtenha um data.frame meninos_altos, que correspondem aos alunos do sexo masculino com altura maior que 1.75m.

In [133]:
# Resolução do Exercício:
alunos
meninos <- alunos[alunos$sexo == "M",]
meninos
meninos_altos <- alunos[ (alunos$altura > 1.75) & (alunos$sexo == "M") ,]
meninos_altos

nome   sexo idade curso                    altura peso clube   IMC     
1 João   M    30    Engenharia Mecatrônica   1.71   88.1 ABC     30.12893
2 Clara  F    24    Engenharia de Computação 1.55   55.2 América 22.97607
3 Miguel M    22    Engenharia de Computação 1.82   72.6 Alecrim 21.91764
4 Ênio   M    21    Engenharia Mecatrônica   1.68   63.2 Tashima 22.39229

nome   sexo idade curso                    altura peso clube   IMC     
1 João   M    30    Engenharia Mecatrônica   1.71   88.1 ABC     30.12893
3 Miguel M    22    Engenharia de Computação 1.82   72.6 Alecrim 21.91764
4 Ênio   M    21    Engenharia Mecatrônica   1.68   63.2 Tashima 22.39229

nome   sexo idade curso                    altura peso clube   IMC     
3 Miguel M    22    Engenharia de Computação 1.82   72.6 Alecrim 21.91764

### 5.4  Algumas Funções Importante
- subset()  - 
- with()
- sapply() e lapply()
- Filter() 
- sort( )
- order( )

#### Função subset()
- Esta função seleciona um sub-frame a partir de uma expressão lógica.
- Estrura geral:	
     subset(nome_do_data_frame, expressao_logica_para_filtrar_linhas,
            select = nomes_das_colunas)

In [129]:
alunos

nome   sexo idade curso                    altura peso clube   IMC     
1 João   M    30    Engenharia Mecatrônica   1.71   88.1 ABC     30.12893
2 Clara  F    24    Engenharia de Computação 1.55   55.2 América 22.97607
3 Miguel M    22    Engenharia de Computação 1.82   72.6 Alecrim 21.91764
4 Ênio   M    21    Engenharia Mecatrônica   1.68   63.2 Tashima 22.39229

In [134]:
# Exemplo de Uso

## alunos[alunos$sexo == "F",]
subset(alunos, sexo == "F")


nome  sexo idade curso                    altura peso clube   IMC     
2 Clara F    24    Engenharia de Computação 1.55   55.2 América 22.97607

In [135]:
# Exemplo de Uso

subset(alunos, sexo == "M" & altura >1.7 )

nome   sexo idade curso                    altura peso clube   IMC     
1 João   M    30    Engenharia Mecatrônica   1.71   88.1 ABC     30.12893
3 Miguel M    22    Engenharia de Computação 1.82   72.6 Alecrim 21.91764

In [136]:
# Exemplo de Uso
# alunos[alunos$sexo == "M", c("nome", "idade")]
subset(alunos, sexo == "M", select = c("nome", "idade"))

nome   idade
1 João   30   
3 Miguel 22   
4 Ênio   21

#### Função with()
- Função para facilitar operações com colunas.


In [137]:
alunos

nome   sexo idade curso                    altura peso clube   IMC     
1 João   M    30    Engenharia Mecatrônica   1.71   88.1 ABC     30.12893
2 Clara  F    24    Engenharia de Computação 1.55   55.2 América 22.97607
3 Miguel M    22    Engenharia de Computação 1.82   72.6 Alecrim 21.91764
4 Ênio   M    21    Engenharia Mecatrônica   1.68   63.2 Tashima 22.39229

In [138]:
# Exemplo de uso

with(alunos, peso/(altura*altura))


[1] 30.12893 22.97607 21.91764 22.39229

In [139]:
# Quatro formas de fazer a mesma coisa

subset(alunos, sexo == "M", select = "idade", drop = TRUE)
with(alunos, idade[sexo == "M"])
alunos$idade[alunos$sexo == "M"]
alunos[alunos$sexo == "M", "idade"]

[1] 30 22 21

[1] 30 22 21

[1] 30 22 21

[1] 30 22 21

#### Funções sapply() e lapply()
- As funções sapply( ) e lapply( ) aplicam uma função nas colunas de um data.frame.
- A diferença é que lapply( ) sempre retorna uma lista.

In [140]:
alunos

nome   sexo idade curso                    altura peso clube   IMC     
1 João   M    30    Engenharia Mecatrônica   1.71   88.1 ABC     30.12893
2 Clara  F    24    Engenharia de Computação 1.55   55.2 América 22.97607
3 Miguel M    22    Engenharia de Computação 1.82   72.6 Alecrim 21.91764
4 Ênio   M    21    Engenharia Mecatrônica   1.68   63.2 Tashima 22.39229

In [143]:
# Aploca a função mean nas colunas altura e peso
sapply(alunos[5:6], mean)

lapply(alunos[5:6], mean)

altura   peso 
 1.690 69.775

$altura
[1] 1.69

$peso
[1] 69.775

#### Função Filter()
- FIltra  apenas aquelas colunas de determinada classe (ou que satisfaçam determinada condição).

In [144]:
# seleciona apenas colunas numéricas
Filter(is.numeric, alunos)

idade altura peso IMC     
1 30    1.71   88.1 30.12893
2 24    1.55   55.2 22.97607
3 22    1.82   72.6 21.91764
4 21    1.68   63.2 22.39229

In [145]:
# seleciona apenas colunas de texto
Filter(is.character, alunos)

nome   sexo curso                    clube  
1 João   M    Engenharia Mecatrônica   ABC    
2 Clara  F    Engenharia de Computação América
3 Miguel M    Engenharia de Computação Alecrim
4 Ênio   M    Engenharia Mecatrônica   Tashima

In [146]:
# aplica a média apenas para variáveis numéricas
sapply(Filter(is.numeric, alunos), mean)

idade   altura     peso      IMC 
24.25000  1.69000 69.77500 24.35373

#### Exercício: Obtenha os maiores valores de idade, altura e peso dos alunos


In [157]:
# Exercício - resolução
alunos

lapply(Filter(is.numeric,alunos[3:6]),max)


nome   sexo idade curso                    altura peso clube   IMC     
1 João   M    30    Engenharia Mecatrônica   1.71   88.1 ABC     30.12893
2 Clara  F    24    Engenharia de Computação 1.55   55.2 América 22.97607
3 Miguel M    22    Engenharia de Computação 1.82   72.6 Alecrim 21.91764
4 Ênio   M    21    Engenharia Mecatrônica   1.68   63.2 Tashima 22.39229

$idade
[1] 30

$altura
[1] 1.82

$peso
[1] 88.1

#### Função sort( )
    - Este comendo faz uma classificação (crescente ou decrescente) de um vetor.
    - sintaxe --> sort(x, decreasing = FALSE, ...)
        - onde x é o vetor a ser classificado, decreasing = false define que a classificação será em ordem crescente e ... significa que outros argumentos podem ser incrementados. 
        - Por exemplo: na.last = NA significa que valores que não foram definidos não vão ser listados. 
        - Outras opções seriam na.last = TRUE (os valores faltantes ficariam após o último valor classificado) e na.last=FALSE  (os valores faltantes ficariam antes do primeiro valor classificado).

In [158]:
amostra <- c(4, 10, 3, -2, NA, 0, NA, 30, -5)
sort(amostra)   #É a classificação simples com os argumentos com seus valores padrões
sort(amostra, decreasing=TRUE, na.last=TRUE)  # ordenar de forma decrescente e comocar os NA no final

[1] -5 -2  0  3  4 10 30

[1] 30 10  4  3  0 -2 -5 NA NA

#### Função order()
    - A função faz uma permutação que rearranja os valores em ordem crescente ou decrescente.
    - A sintaxe da função order é:
        - order(..., na.last = TRUE, decreasing = FALSE)

In [159]:
# exemplo de uso da função order()
letras <-c('g', 'a', 'z', 'c')
a <- order(letras)
b <- sort(letras)
c <- letras[order(letras)]
letras
a
b
c

[1] "g" "a" "z" "c"

[1] 2 4 1 3

[1] "a" "c" "g" "z"

[1] "a" "c" "g" "z"

- Mais exemplos com a função order().

In [160]:
#set.seed(1)
dados <- data.frame(w=rep(c("A", "B"), 2), x= rep(c("D", "C"), 2), y= rnorm(4), z=rnorm(4),
                    stringsAsFactors=FALSE)
dados

w x y           z        
1 A D -0.19599486 0.0649673
2 B C  0.02078654 0.8271571
3 A D  1.25574295 1.0892108
4 B C -0.98491369 0.7210677

In [161]:
# Solução 1
# No caso, ordena de acordo por w em ordem alfabética inversa, x em ordem alfabética e y em ordem decrescente. Se quiser que tudo seja na mesma ordem, basta um TRUE ou FALSE, que valerá para todos.

dados[order(dados$w, dados$x, dados$y, decreasing=c(TRUE, FALSE, TRUE)), ] 


w x y           z        
2 B C  0.02078654 0.8271571
4 B C -0.98491369 0.7210677
3 A D  1.25574295 1.0892108
1 A D -0.19599486 0.0649673

In [162]:
# caso se queira ordenar apenas uma coluna

dados[order(dados$z, decreasing=TRUE),]

w x y           z        
3 A D  1.25574295 1.0892108
2 B C  0.02078654 0.8271571
4 B C -0.98491369 0.7210677
1 A D -0.19599486 0.0649673

In [163]:
# Usando o pacote plyr
library(plyr)
arrange(dados,desc(z))
 

ERROR: Error in library(plyr): there is no package called ‘plyr’


In [164]:
# Usando a função arrange - o default é ordenar de forma crescente
arrange(dados,desc(w),z)


ERROR: Error in eval(expr, envir, enclos): não foi possível encontrar a função "arrange"


## 6. Controle de Fluxo em R

- If
- Loop while
- Loop for


### 6.1 Comando IF-ELSE:

if (logic_condition) 

 { 
   conjunto de comandos
 }  
      
else 
 {
  conjunto de comandos
 }

In [ ]:
# Variables related to your last day of recordings
medium <- "LinkedIn"
num_views <- 14

# Control structure for medium
if (medium == "LinkedIn") {
  print("Showing LinkedIn information")
} else if (medium == "Facebook") {
  # Add code to print correct string when condition is TRUE
   print("Showing Facebook information")
} else {
  print("Unknown medium")
}

# Control structure for num_views
if (num_views > 15) {
  print("You're popular!")
} else if (num_views <= 15 & num_views > 10) {
  # Add code to print correct string when condition is TRUE
   print("Your number of views is average")
} else {
  print("Try to be more visible!")
}

### 6.2 Comando WHILE

while (logic_condition)

 { 
 
   conjunto de comandos
   
 }

In [ ]:
# Initialize the speed variable
speed <- 64

# Code the while loop
while ( speed > 30) {
  print("Slow down!")
  speed <- speed -7
}

# Print out the speed variable
speed

#### Exemplos com WHILE e IF

In [ ]:
# Initialize the speed variable
speed <- 64

# Extend/adapt the while loop
while (speed > 30) {
  print(paste("Your speed is",speed))
  if ( speed > 48) {
    print("Slow down big time!")
    speed <- speed - 11
    
  } else {
    
    print("Slow down!")
    speed <- speed - 6
  }
}

#### Exemplos com BREAK no loop

In [ ]:
# Initialize the speed variable
speed <- 88

while (speed > 30) {
  print(paste("Your speed is", speed))
  
  # Break the while loop when speed exceeds 80
  if (speed > 80 ) {break
    
  }
  
  if (speed > 48) {
    print("Slow down big time!")
    speed <- speed - 11
  } else {
    print("Slow down!")
    speed <- speed - 6
  }
}

### 6.3 Comando FOR

for(i in sequencia)

 { 
   
   conjunto de comandos
   
 }

In [ ]:
n1 <- 1
n2 <- 6
for(i in n1:n2){
  print(i)
}

In [ ]:
n <- 8
for(letra in letters[1:n]){
  print(letra)
}

## 7. Função em R

- Em construção
